"""Data-quality report at title grain — generated, not hand-written."""

from __future__ import annotations

from pathlib import Path

import pandas as pd

from .clean import PROCESSED, ROOT


def _pct(n: int, d: int) -> str:
    return f"{n:,} ({n / d:.1%})"


def write_quality_report(titles: pd.DataFrame, genres: pd.DataFrame, countries: pd.DataFrame) -> Path:
    n = len(titles)
    director_by_type = titles.groupby("type")["director_unknown"].mean().mul(100).round(1)
    country_by_type = titles.groupby("type")["country_unknown"].mean().mul(100).round(1)
    peak_year = int(titles["year_added"].value_counts().idxmax())
    peak_n = int(titles["year_added"].value_counts().max())
    rating_counts = titles["rating"].fillna("Unknown").value_counts()
    band_counts = titles["maturity_band"].value_counts()
    top_countries = countries["country_credit"].value_counts().head(10)
    top_genres = genres["genre"].value_counts().head(10)

    lines = [
        "# Data quality report",
        "",
        "Generated by `python -m netflix_catalog`. Do not edit by hand.",
        "",
        "## Scope",
        "",
        f"- Titles: **{n:,}** (Movie {int((titles['type']=='Movie').sum()):,} · TV Show {int((titles['type']=='TV Show').sum()):,})",
        f"- Genre-credit rows: **{len(genres):,}** (mean tags/title {titles['n_genre_tags'].mean():.2f})",
        f"- Country-credit rows: **{len(countries):,}** (multi-country titles {(titles['n_countries']>1).sum():,})",
        f"- `date_added` span: {titles['date_added_parsed'].min().date()} → {titles['date_added_parsed'].max().date()}",
        f"- Duplicate `show_id`: {int(titles['show_id'].duplicated().sum())}",
        "",
        "## Missingness (kept as NULL in analytic tables)",
        "",
        "| Field | Nulls | Share | Pattern |",
        "|---|---:|---:|---|",
        f"| director | {int(titles['director_unknown'].sum()):,} | {titles['director_unknown'].mean():.1%} | TV Show {director_by_type.get('TV Show', 0)}% vs Movie {director_by_type.get('Movie', 0)}% |",
        f"| country | {int(titles['country_unknown'].sum()):,} | {titles['country_unknown'].mean():.1%} | TV Show {country_by_type.get('TV Show', 0)}% vs Movie {country_by_type.get('Movie', 0)}% |",
        f"| cast | {int(titles['cast_unknown'].sum()):,} | {titles['cast_unknown'].mean():.1%} | Higher on TV Shows |",
        f"| date_added | {int(titles['date_added_parsed'].isna().sum()):,} | {titles['date_added_parsed'].isna().mean():.1%} | Flag, do not impute |",
        f"| rating (after recode) | {int(titles['rating'].isna().sum()):,} | {titles['rating'].isna().mean():.1%} | Includes 3 duration-swap rows |",
        "",
        "## Recodes applied",
        "",
        f"- Duration leaked into `rating`: **{int(titles['rating_was_duration'].sum())}** rows restored to `duration`, `rating` set to NULL.",
        "- Vietnamese display fills (`Không có thông tin`, `Không xác định`) are **not** used in analytic tables.",
        "- Tableau-friendly extract uses English `Unknown` at viz-layer only (`data/processed/netflix_titles_tableau.csv`).",
        "",
        "## Catalog clocks",
        "",
        f"- Peak add-year: **{peak_year}** ({peak_n:,} titles). 2021 is truncated at 25 September.",
        f"- Family-adjacent titles: {_pct(int(titles['family_adjacent'].sum()), n)}",
        f"- TV-MA + TV-14: {_pct(int(titles['rating'].isin(['TV-MA','TV-14']).sum()), n)}",
        "",
        "### Maturity band (derived; not viewers)",
        "",
        "| Band | Titles |",
        "|---|---:|",
    ]
    for band, count in band_counts.items():
        lines.append(f"| {band} | {count:,} |")

    lines += [
        "",
        "### Rating (title grain)",
        "",
        "| Rating | Titles |",
        "|---|---:|",
    ]
    for rating, count in rating_counts.items():
        lines.append(f"| {rating} | {count:,} |")

    lines += [
        "",
        "### Top production-country credits (exploded; Unknown excluded)",
        "",
        "| Country | Credits |",
        "|---|---:|",
    ]
    for country, count in top_countries.items():
        lines.append(f"| {country} | {count:,} |")

    lines += [
        "",
        "### Top genre tags (exploded incidences)",
        "",
        "| Genre | Tags |",
        "|---|---:|",
    ]
    for genre, count in top_genres.items():
        lines.append(f"| {genre} | {count:,} |")

    lines += [
        "",
        "## Non-claims",
        "",
        "- No watch-time, completion, cost, or subscriber measures exist in this extract.",
        "- `maturity_band` is a recode of title `rating`, not an audience segment.",
        "- Country credits are not filming locations and not mutually exclusive market shares.",
        "",
    ]

    out = PROCESSED / "quality_report.md"
    out.write_text("\n".join(lines) + "\n")
    docs = ROOT / "docs" / "DATA_QUALITY.md"
    docs.write_text(out.read_text())
    return out
